workflows:
  ios-capacitor:
    name: iOS Capacitor Build

    integrations:
      app_store_connect: L'Olympe Padel

    environment:
      xcode: latest
      groups:
        - SUPABASE
      ios_signing:
        distribution_type: app_store
        bundle_identifier: fr.olympepadel.app
        #profile: olympe_padel_app_store

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm run build
          npx cap sync ios

      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
