workflows:
  ios-capacitor:
    name: iOS Capacitor Build

    integrations:
      app_store_connect: L'Olympe Padel

    environment:
      xcode: latest
      groups:
        - SUPABASE
      ios_signing:
        distribution_type: app_store
        bundle_identifier: fr.olympepadel.app

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm run build
          npx cap sync ios

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
