workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    integrations:
      app_store_connect: L'Olympe Padel
    environment:
      xcode: latest
      groups:
        - SUPABASE
      vars:
        APP_VERSION: "1.0.0"
        APP_BUILD_NUMBER: "2"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: fr.olympepadel.app
    scripts:
      - name: Install dependencies
        script: |
          npm install
     
      - name: Generate assets (icons & splash)
        script: |
          npx capacitor-assets generate

      - name: Build web app
        script: |
          npm run build
      
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
