workflows:
  ios-capacitor:
    name: iOS Capacitor Build

    integrations:
      app_store_connect: WBRQPCUBCA

    environment:
      xcode: latest
      groups:
        - SUPABASE

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm run build
          npx cap sync ios

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
